name: Main

on:
  push:
    branches: 'master'
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "SwitchViewSKSE"
      FOMOD_MOD_AUTHOR: "Styyx"
      FOMOD_MOD_NEXUS_ID: "99157"
      FOMOD_REQUIRED_INSTALLATION_DIR: "Skyrim/Data"
      PUBLISH_ARCHIVE_TYPE: '7z'
      FOMOD_SE_MIN_GAME_VERSION: '1.5'
      FOMOD_AE_NAME: 'SSE v1.6.640+ ("Anniversary Edition")'
      FOMOD_AE_DESCR: 'Select this if you are using Skyrim Anniversary Edition v1.6.640 or higher.'
      FOMOD_AE_MIN_GAME_VERSION: '1.6'
      VCPKG_COMMIT_ID: 'b7dba7f9aad09a56900f21cd78cfda1258e54e38'
